// Metadata 类型用于声明页面级 SEO 元信息。
import type { Metadata } from "next";
// localFont 用于加载本地字体文件并注入 CSS 变量。
import localFont from "next/font/local";
// 全局样式文件（对整个应用生效）。
import "./globals.css";

// 加载无衬线字体，并暴露为 CSS 变量 --font-geist-sans。
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
// 加载等宽字体，并暴露为 CSS 变量 --font-geist-mono。
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// 声明全局页面元数据（会注入到 <head> 中）。
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 根布局组件：所有页面都会被它包裹。
export default function RootLayout({
  children,
}: Readonly<{
  // children 代表当前路由页面内容。
  children: React.ReactNode;
}>) {
  return (
    // 根 html 标签，lang 指定页面主语言。
    <html lang="en">
      {/* 给 body 注入字体变量，页面内即可使用对应字体。 */}
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* 渲染具体页面内容。 */}
        {children}
      </body>
    </html>
  );
}
